--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-24-2020   
--------------------------------------------------------
REM INSERTING into INVEM.CHAMP
SET DEFINE OFF;
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (34,'말자하','마법사, 암살자','미드, 서폿','침묵, 제압','Malzahar, The Prophet of the void');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (35,'말파이트','탱커, 전사','탑, 미드, 서포터','띄우기, 보호막, 둔화, 탈출','Malphite, The Shard of the Monolith');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (36,'모데카이저','전사, 마법사','탑, 미드','보호막','Mordekaiser, The Iron Revenant');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (37,'모르가나','마법사, 서포터','미드, 서포터','보호막, 둔화, 속박, 기절, 치유','Morgana, The Fallen');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (38,'문도 박사','전사, 탱커','탑, 정글','둔화, 치유','Dr. Mundo, The Madman of Zaun');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (39,'미스 포츈','원거리','미드, 봇, 서포터','둔화','Miss Fortune, The Bounty Hunter');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (40,'바드','서포터','서포터','치유, 둔화, 기절','Bard, the Wandering Caretaker');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (41,'바루스','원거리','미드, 봇','둔화, 속박','Varus, The Arrow of Retribution');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (42,'바이','전사, 암살자','정글','보호막, 제압, 탈출, 밀치기','Vi, the Piltover Enforcer');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (43,'베이가','마법사, 서포터','미드, 서포터','기절','Veigar, The Tiny Master of Evil');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (44,'베인','원거리, 암살자','봇, 탑','탈출, 밀치기, 은신, 기절','Vayne, The Night Hunter');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (45,'벨코즈','마법사, 서포터','미드, 서포터','띄우기, 둔화, 밀치기','Vel''Koz, The Eye of the Void');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (46,'볼리베어','전사, 탱커','탑, 정글, 서포터','공포, 치유, 던지기, 둔화','Volibear, The Thunder''s Roar');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (47,'브라움','서포터, 탱커','서포터','띄우기, 둔화, 기절','Braum, the Heart of the Freljord');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (48,'브랜드','마법사','미드, 서포터','기절','Brand, The Burning Vengeance');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (49,'블라디미르','마법사, 탱커','미드, 탑','치유, 둔화','Vladimir, The Crimson Reaper');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (50,'블리츠크랭크','탱커, 전사','서포터','띄우기, 보호막, 침묵','Blitzcrank, The Great Steam Golem');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (63,'스웨인','마법사, 전사','탑, 미드, 서포터','치유, 둔화, 속박','Swain, The Master Tactician');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (64,'스카너','전사, 탱커','정글','보호막, 둔화, 제압, 기절','Skarner, The Crystal Vanguard');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (65,'시비르','원거리','봇','보호막','Sivir, The Battle Mistress');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (66,'신 짜오','전사, 암살자','정글, 미드','띄우기, 치유, 둔화, 밀치기, 기절','Xin Zhao, The Seneschal of Demacia');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (51,'빅토르','마법사','탑, 미드, 봇','보호막, 침묵, 기절, 둔화, 띄우기','Viktor, The Machine Herald Revealed');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (52,'뽀삐','전사','탑, 정글, 서포터','밀치기, 기절, 보호막, 둔화, 띄우기','Poppy, Keeper of the Hammer');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (53,'사이온','전사','탑, 서포터','보호막, 기절, 둔화, 띄우기','Sion, The Undead Champion');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (54,'사일러스','마법사','탑, 미드, 정글','기절, 보호막, 치유','Sylas, the Unshackled');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (55,'샤코','암살자','탑, 정글, 서포터','탈출, 공포, 둔화, 은신','Shaco, The Demon Jester');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (56,'세나','원거리, 서포터','봇, 서포터','치유, 보호막, 속박, 은신','Senna, the Redeemer');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (57,'세주아니','탱커, 전사','정글','띄우기, 탈출, 둔화, 기절','Sejuani, Fury of the North');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (58,'세트','전사, 탱커','탑, 미드, 정글, 서포터','띄우기, 치유, 보호막, 기절','Sett, The Boss');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (59,'소나','서포터, 마법사','탑, 서포터','치유, 둔화, 기절, 보호막','Sona, The Maven of the Strings');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (60,'소라카','서포터, 마법사','탑, 서포터','치유, 침묵, 둔화, 속박','Soraka, The Starchild');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (61,'쉔','탱커, 전사','탑, 서포터','치유, 탈출, 보호막, 도발','Shen, The Eye of Twilight');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (62,'쉬바나','전사, 탱커','탑, 정글','탈출, 밀치기','Shyvana, The Half-Dragon');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (67,'신드라','마법사','미드, 봇','기절, 둔화, 밀치기','Syndra, the Dark Sovereign');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (68,'신지드','탱커, 전사','탑','둔화, 던지기, 치유, 속박','Singed, The Mad Chemist');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (69,'쓰레쉬','서포터, 전사','서포터','밀치기, 둔화, 보호막, 기절, 정찰','Thresh, The Chain Warden');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (70,'아리','마법사, 암살자','미드','탈출, 치유, 도발','Ahri, The Nine-Tailed Fox');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (71,'아무무','탱커, 마법사','정글','기절, 속박','Amumu, The Sad Mummy');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (72,'아우렐리온 솔','마법사','미드','밀치기, 둔화, 기절','Aurelion Sol, The Star Forger');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (73,'아이번','서포터, 마법사','정글','띄우기, 보호막, 둔화, 속박','Ivern, The Green Father');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (74,'아지르','마법사, 원거리','미드','둔화, 밀치기','Azir, the Emperor of the Sands');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (75,'아칼리','암살자','탑, 미드','둔화, 은신','Akali, The Fist of Shadow');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (76,'아트록스','전사, 탱커','탑, 미드, 정글','띄우기, 탈출, 치휴, 둔화','Aatrox, the Darkin Blade');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (77,'아펠리오스','원거리','봇','치유, 보호막, 둔화, 속박','Aphelios, the Weapon of the Faithful');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (78,'알리스타','전사, 서포터','서포터','띄우기, 치유, 밀치기','Alistar, The Minotaur');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (79,'애니','마법사','미드, 서포터','기절, 보호막','Annie, The Dark Child');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (80,'애니비아','마법사','미드','둔화, 기절','Anivia, The Cryophoenix');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (81,'애쉬','원거리, 서포터','봇, 서포터','정찰, 둔화, 기절','Ashe, The Frost Archer');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (82,'야스오','전사, 암살자','미드, 탑, 봇','보호막, 띄우기, 제압','Yasuo, the Unforgiven');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (1,'가렌','전사, 탱커','탑, 미드','침묵','Garen, The Might of Demacia');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (2,'갈리오','탱커, 마법사','미드, 서포터','도발, 보호막, 띄우기','Galio, THE COLOSSUS');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (3,'갱플랭크','전사','미드, 탑','치유, 둔화','Gangplank, The Saltwater Scourge');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (4,'그라가스','전사, 마법사','정글, 미드, 서포터','탈출, 밀치기, 둔화, 기절','Gragas, The Rabble Rouser');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (5,'그레이브즈','원거리, 전사','정글','탈출, 실명, 둔화','Graves, The Outlaw');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (6,'나르','전사, 원거리','탑','둔화, 탈출, 밀치기, 기절','Gnar, the Missing Link');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (7,'나미','서포터, 마법사','서포터','띄우기, 기절, 치유, 둔화','Nami, the Tidecaller');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (8,'나서스','전사, 탱커','탑, 정글','둔화','Nasus, The Curator of the Sands');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (9,'노틸러스','탱커, 전사','미드, 서포터','띄우기, 둔화, 보호막, 속박, 기절','Nautilus, The Titan of the Depths');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (10,'녹턴','암살자, 전사','정글, 미드','보호막, 공포','Nocturne, The Eternal Nightmare');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (11,'누누와 월럼프','서포터, 전사','정글, 서포터','치유, 둔화, 띄우기','Nunu & Willump, the Boy and his Yeti');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (12,'니달리','암살자, 서포터','정글, 미드, 서포터','탈출, 치유, 정찰','Nidalee, The Bestial Huntress');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (13,'니코','마법사, 서포터','미드, 서포터','속박, 기절, 둔화, 보호막','Neeko, the Curious Chameleon');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (14,'다리우스','전사, 탱커','탑, 미드','둔화','Darius, The Hand of Noxus');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (15,'다이애나','마법사, 암살자','미드, 정글','띄우기, 보호막','Diana, Scorn of the Moon');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (16,'드레이븐','원거리','봇','밀치기, 둔화','Draven, The Glorious Executioner');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (17,'라이즈','마법사, 전사','탑, 미드','속박, 치유','Ryze, The Rogue Mage');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (18,'라칸','서포터, 마법사','서포터','띄우기, 치유, 보호막, 도박','Rakan, The Charmer');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (19,'람머스','탱커, 전사','탑, 정글','밀치기, 도발, 둔화','Rammus, The Armordillo');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (20,'럭스','마법사, 서포터','미드, 서포터','정찰, 둔화, 속박, 보호막','Lux, The Lady of Luminosity');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (21,'럼블','전사, 마법사','탑, 미드, 서포터','보호막, 둔화','Rumble, The Mechanized Menace');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (22,'레넥톤','전사, 탱커','탑, 미드','탈출, 치유, 기절','Renekton, The Butcher of the Sands');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (23,'레오나','탱커, 서포터','서포터','둔화, 기절','Leona, The Radiant Dawn');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (24,'렉사이','전사','정글','띄우기, 정찰, 탈출','Rek''Sai, the Void Burrower');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (25,'렝가','전사, 암살자','탑, 정글','치유, 둔화, 속박, 은신','Rengar, the Pridestalker');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (26,'루시안','원거리','봇','탈출','Lucian, the Purifier');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (27,'룰루','서포터, 마법사','미드, 서포터','띄우기, 보호막, 둔화','Lulu, The Fae Sorceress');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (28,'르블랑','암살자, 마법사','미드','탈출, 둔화, 속박, 은신','LeBlanc, The Deceiver');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (29,'리 신','전사, 암살자','정글, 미드','탈출, 밀치기, 보호막, 둔화','Lee Sin, The Blind Monk');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (30,'리븐','전사, 암살자','탑, 미드','기절, 탈출, 보호막, 띄우기','Riven, The Exile');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (31,'리산드라','마법사','미드, 탑','둔화, 속박, 기절, 탈출, 치유','Lissandra, the Ice Witch');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (32,'마스터 이','암살자, 전사','정글','치유','Master Yi, The Wuju Bladesman');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (33,'마오카이','탱커, 마법사','탑, 정글, 서포터','밀치기, 정찰, 보호막, 속박','Maokai, The Twisted Treant');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (147,'하이머딩거','마법사, 서포터','탑, 미드, 봇','정찰, 둔화, 기절','Heimerdinger, The Revered Inventor');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (148,'헤카림','전사, 탱커','탑, 정글','밀치기, 공포, 탈출, 치유','Hecarim, The Shadow of War');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (83,'에코','암살자, 마법사','정글, 미드','치유, 둔화, 기절, 보호막, 탈출','Ekko, the Boy Who Shattered Time');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (84,'엘리스','마법사, 전사','정글','기절, 치유','Elise, The Spider Queen');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (85,'오공','전사, 탱커','정글, 미드','띄우기, 은식','Wukong, The Monkey King');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (86,'오른','전사, 탱커','탑, 미드, 서포터','띄우기, 밀치기, 보호막','Ornn, the Fire Below the Mountain');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (87,'오리아나','마법사, 서포터','미드','띄우기, 둔화, 보호막, 정찰','Orianna, The Lady of Clockwork');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (88,'올라프','전사, 탱커','탑, 정글','치유, 둔화','Olaf, The Berserker');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (89,'요릭','전사, 탱커','탑','밀치기, 둔화, 치유','Yorick, Shepherd of the lost souls');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (90,'우디르','전사, 탱커','정글','보호막, 치유, 기절','Udyr, The Animal Spirit');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (91,'우르곳','원거리, 전사','탑','보호막, 둔화, 기절, 공포','Urgot, The Dreadnought');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (92,'워윅','전사, 탱커','정글','치유, 정찰, 제압, 공포','Warwick, The Blood Hunter');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (93,'유미','마법사','서포터','보호막, 둔화, 속박, 치유','Yummi, the Magical Cat');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (94,'이렐리아','전사, 암살자','탑, 미드, 봇','치유, 둔화, 기절','Irelia, The Will of the Blades');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (95,'이블린','암살자, 마법사','정글','둔화, 은신, 보호막','Evelynn, The Widowmaker');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (96,'이즈리얼','원거리, 마법사','미드, 봇','탈출','Ezreal, The Prodigal Explorer');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (97,'일라오이','전사, 탱커','탑','둔화','Illaoi, the Kraken Priestess');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (98,'자르반 4세','탱커, 전사','정글','띄우기, 정찰, 보호막, 둔화, 탈출','Jarvan IV, The Exemplar of Demacia');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (99,'자야','원거리','봇','속박','Xayah, The Rebel');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (100,'자이라','마법사, 서포터','미드, 서포터','정찰, 둔화, 속박, 띄우기','Zyra, Rise of the Thorns');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (101,'자크','탱커, 전사','정글, 서포터','띄우기, 탈출, 둔화, 치유','Zac, the Secret Weapon');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (102,'잔나','서포터, 마법사','서포터','띄우기, 치유, 밀치기, 보호막, 둔화','Janna, The Storm''s Fury');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (103,'잭스','전사, 암살자','탑, 정글','탈출, 기절','Jax, The Grandmaster at Arms');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (104,'제드','암살자, 전사','탑, 미드','탈출, 둔화','Zed, the Master of Shadows');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (105,'제라스','마법사, 암살자','미드, 서포터','둔화, 기절','Xerath, The Magus Ascendant');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (106,'제이스','전사, 원거리','탐, 미드','밀치기, 둔화','Jayce, The Defender of Tomorrow');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (107,'조이','마법사, 서포터','미드','기절, 둔화','Zoe, the Aspect of Twilight');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (108,'직스','마법사','미드, 봇','밀치기, 둔화','Ziggs, The Hexplosives Expert');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (109,'진','원거리, 암살자','봇','둔화, 속박','Jhin, the Virtuoso');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (110,'질리언','서포터, 마법사','미드, 서포터','둔화, 기절','Zilean, The Chronokeeper');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (111,'징크스','원거리','봇','둔화, 속박','Jinx, the Loose Cannon');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (112,'초가스','탱커, 마법사','탑, 미드','띄우기, 침묵, 둔화','Cho''Gath, The Terror of the Void');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (113,'카르마','마법사, 서포터','탑, 미드, 서포터','둔화, 속박','Karma, The Enlightened One');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (114,'카밀','전사, 암살자','탑, 정글','밀치기, 보호막, 둔화, 기절','Camille, The Steel Shadow');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (115,'카사딘','암살자, 마법사','탑, 미드','보호막, 둔화, 침묵','Kassadin, The Void Walker');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (116,'카서스','마법사','미드, 정글','둔화','Karthus, The Deathsinger');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (117,'카시오페아','마법사','미드, 봇','둔화, 기절, 정찰','Cassiopeia, The Serpent''s Embrace');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (118,'카이사','원거리','봇','보호막, 은신','Kai’Sa, Daughter of the Void');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (119,'카직스','암살자, 전사','미드, 정글','은신, 탈출, 치유, 둔화','Khazix, the Voidreaver');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (120,'카타리나','암살자, 마법사','미드','탈출','Katarina, The sinister');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (121,'칼리스타','원거리','봇, 탑','둔화, 밀치기, 띄우기, 정찰, 탈출','Kalista, the Spear of Vengeance');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (122,'케넨','마법사, 원거리','탑, 미드, 봇','기절','Kennen, The Heart of the Tempest');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (123,'케이틀린','원거리','봇','탈출, 둔화, 속박','Caitlyn, The Sheriff of Piltover');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (124,'케인','전사, 암살자','정글','띄우기, 둔화, 은신','Kayn, the Shadow Reaper');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (125,'케일','전사','탑','치유, 둔화','Kayle, The Righteous');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (126,'코그모','원거리, 마법사','미드, 봇','정찰, 둔화','Kog''Maw, The Mouth of the Abyss');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (127,'코르키','원거리','미드, 봇','탈출, 정찰, 밀치기, 둔화','Corki, The Daring Bombardier');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (128,'퀸','원거리, 전사','탑, 봇','실명, 정찰, 둔화','Quinn, Demacia''s Wings');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (129,'클레드','전사, 탱커','탑','띄우기, 밀치기, 둔화, 보호막, 탈출','Kled, The Cantankerous Cavalier');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (130,'키아나','암살자','미드, 정글','밀치기, 둔화, 속박, 은신, 기절','Qiyana, Empress of the Elements');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (131,'킨드레드','원거리','정글','치유, 둔화, 탈출','Kindred, The Eternal Hunters');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (132,'타릭','서포터, 전사','서포터','치유, 기절','Taric, The Shield of Valoran');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (133,'탈론','암살자, 전사','미드','둔화, 은신','Talon, The Blade''s Shadow');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (134,'탈리야','마법사','미드, 정글','띄우기, 밀치기, 둔화','Taliyah, The Stoneweaver');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (135,'탐켄치','서포터, 탱커','탑, 서포터','치유, 둔화, 제압, 기절','Tahm Kench, the River King');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (136,'트런들','전사, 탱커','탑, 정글, 서포터','둔화, 밀치기','Trundle, The Cursed Troll');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (137,'트리스타나','원거리','미드, 봇','탈출, 밀치기, 둔화','Tristana, The Megling Gunner');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (138,'트린다미어','전사, 암살자','탑, 정글','치유, 둔화, 탈출','Tryndamere, The Barbarian King');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (139,'트위스티드 페이트','마법사','미드','정찰, 둔화, 기절, 탈출','Twisted Fate, The Card Master');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (140,'트위치','원거리','봇','둔화, 은신','Twitch, The Plague Rat');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (141,'티모','원거리, 암살자','탑','실명, 정찰, 둔화, 은신','Teemo, The Swift Scout');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (142,'파이크','서포터, 암살자','서포터','은신','Pyke, the Bloodharbor Ripper');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (143,'판테온','전사, 암살자','탑, 미드','기절, 둔화','Pantheon, The Artisan of War');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (144,'피들스틱','마법사, 서포터','탑, 정글, 서포터','공포, 침묵, 치유','Fiddlesticks, The Harbinger of Doom');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (145,'피오라','전사, 암살자','탑','치유, 둔화, 기절','Fiora, The Grand Duelist');
Insert into INVEM.CHAMP (NO,CHAMP,ROLE,LANE,SKILL,NICKNAME) values (146,'피즈','암살자, 마법사','미드','탈출, 둔화, 밀치기','Fizz, The Tidal Trickster');
